In [2]:
import numpy as np

In [3]:
array = np.array([1, 2, 3, 4 ,5, 6])
array

array([1, 2, 3, 4, 5, 6])

In [4]:
arrays_dividos = np.split(array, 3)
arrays_dividos

[array([1, 2]), array([3, 4]), array([5, 6])]

In [5]:
for i, value in enumerate(arrays_dividos):
    print(f"Parte {i+1}-> {value}")

Parte 1-> [1 2]
Parte 2-> [3 4]
Parte 3-> [5 6]


In [25]:
# Criando um array 1d com temperaturas diarias de um mês (30 dias)
temperaturas = np.array([22, 23, 25, 20 ,19 ,21, 22,
                        24, 26, 27, 25, 22, 
                        20, 18, 19, 20, 21,
                        22, 23, 24, 25, 26,
                        27, 28, 29, 30, 29,
                        28, 27, 26, 25, 24])
temperaturas

array([22, 23, 25, 20, 19, 21, 22, 24, 26, 27, 25, 22, 20, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 29, 28, 27, 26, 25, 24])

In [27]:
# Dividindo as temperatuas em 4 semanas
semanas = np.split(temperaturas, 4)
semanas

[array([22, 23, 25, 20, 19, 21, 22, 24]),
 array([26, 27, 25, 22, 20, 18, 19, 20]),
 array([21, 22, 23, 24, 25, 26, 27, 28]),
 array([29, 30, 29, 28, 27, 26, 25, 24])]

In [28]:
for i, value in enumerate(semanas, 1):
    print(f"Semana {i}: {value}")

Semana 1: [22 23 25 20 19 21 22 24]
Semana 2: [26 27 25 22 20 18 19 20]
Semana 3: [21 22 23 24 25 26 27 28]
Semana 4: [29 30 29 28 27 26 25 24]


In [29]:
medias_semanas = [np.mean(semanas) for semanas in semanas]
medias_semanas

[np.float64(22.0), np.float64(22.125), np.float64(24.5), np.float64(27.25)]

In [31]:
for i, value in enumerate(medias_semanas, 1):
    print(f"Média da Semana {i}: { value: .2f}ºC")

Média da Semana 1:  22.00ºC
Média da Semana 2:  22.12ºC
Média da Semana 3:  24.50ºC
Média da Semana 4:  27.25ºC
