Copy   
- Uma nova cópia do array é criada em memória.
- Isso significa que as 2 matrizes(original e copia) são indepentes uma da outra.

View
- Não é criada em uma nova cópia de array na memória. A view compartilha os mesmo dados que o array original.

In [2]:
import numpy as np

In [3]:
array_original = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])
array_original

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# 1- Cópia Rasa
array_view = array_original[1: , 1:]
array_view

array([[5, 6],
       [8, 9]])

In [5]:
# 2- Cópia Profunda (Copy)
array_copia = array_original.copy()
array_copia

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
array_copia[0 ,0] = 100
array_copia

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])